name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Latest stable Python version - update this when new Python versions are released
  LATEST_PYTHON_VERSION: "3.13"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # All-in-one job that runs validation, quality checks, testing, and documentation
  ci-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - uses: actions/checkout@v4
    
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.LATEST_PYTHON_VERSION }}
    
    # Step 1: Basic structure validation
    - name: Validate package structure
      run: |
        python validate_structure.py
    
    # Step 2: Install system dependencies for ta-lib (needed for quality checks and testing)
    - name: Install system dependencies for ta-lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git
        git clone https://github.com/ta-lib/ta-lib.git
        cd ta-lib
        if [ ! -f configure ]; then
          chmod +x autogen.sh
          ./autogen.sh
        fi
        ./configure --prefix=/usr
        make
        sudo make install
        sudo ldconfig

    # Step 3: Install Python dependencies
    - name: Install dependencies and quality tools
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas
        pip install -r requirements.txt
        pip install TA-Lib
        pip install flake8 black
        pip install -e .
    
    # Step 4: Code quality checks
    - name: Run flake8 linting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 pandas_ta_classic --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings for non-critical issues
        flake8 pandas_ta_classic --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=pandas_ta_classic/__init__.py
    
    - name: Check code formatting with black
      run: |
        black --check --diff pandas_ta_classic/
    
    # Step 5: Generate Python version matrix for testing
    - name: Generate Python version matrix
      id: versions
      run: |
        # Extract minor version from LATEST_PYTHON_VERSION (e.g., "3.13" -> "13")
        latest="${{ env.LATEST_PYTHON_VERSION }}"
        minor_version=$(echo "$latest" | cut -d'.' -f2)
        
        # Generate 5 versions: latest and 4 previous minor versions
        versions="["
        for i in {4..0}; do
          version_num=$((minor_version - i))
          if [ $i -eq 0 ]; then
            versions="${versions}\"3.${version_num}\""
          else
            versions="${versions}\"3.${version_num}\", "
          fi
        done
        versions="${versions}]"
        
        echo "python-versions=$versions" >> $GITHUB_OUTPUT
        echo "Generated Python versions: $versions"
    
    # Step 6: Update setup.py with dynamic Python classifiers
    - name: Update setup.py with dynamic Python classifiers
      run: |
        python << 'EOF'
        # Simple approach: read setup.py, find Python classifier lines, and replace them
        latest_version = "${{ env.LATEST_PYTHON_VERSION }}"
        minor_version = int(latest_version.split('.')[1])
        
        # Generate the 5 versions we want
        target_versions = []
        for i in range(4, -1, -1):  # 4, 3, 2, 1, 0
            version_num = minor_version - i
            target_versions.append(f"3.{version_num}")
        
        # Read setup.py
        with open('setup.py', 'r') as f:
            content = f.read()
        
        # Find and replace each Python classifier line
        lines = content.split('\n')
        version_index = 0
        
        for i, line in enumerate(lines):
            if '"Programming Language :: Python :: 3.' in line and version_index < len(target_versions):
                # Replace the version number in this line
                import re
                new_line = re.sub(r'3\.\d+', target_versions[version_index], line)
                lines[i] = new_line
                version_index += 1
        
        # Write back to setup.py
        with open('setup.py', 'w') as f:
            f.write('\n'.join(lines))
        
        print(f"Updated setup.py with Python versions: {', '.join(target_versions)}")
        
        # Verify the changes
        with open('setup.py', 'r') as f:
            for line_num, line in enumerate(f, 1):
                if '"Programming Language :: Python :: 3.' in line:
                    print(f"Line {line_num}: {line.strip()}")
        EOF
    
    # Step 7: Run comprehensive tests
    - name: Run full test suite
      run: |
        python -m unittest discover tests/ -v
    
    # Step 8: Test package installation and performance tests
    - name: Test package installation and performance
      run: |
        python -c "import pandas_ta_classic as ta; print('Package imported successfully')"
        python -m unittest tests.test_indicator_performance -v
    
    # Step 9: Build documentation - Jekyll (only on main branch)
    - name: Setup Pages (main branch only)
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Build with Jekyll (main branch only)
      if: github.ref == 'refs/heads/main'
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
      
    - name: Debug Jekyll build output (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Jekyll build completed. Checking _site directory:"
        ls -la ./_site/ || echo "No _site directory found"
        if [ -d "./_site" ]; then
          echo "Files in _site:"
          find ./_site -type f | head -10
        fi
        
    - name: Upload Jekyll artifact (main branch only)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site
    
    # Step 10: Build Sphinx documentation (only on main branch)
    - name: Install Sphinx dependencies (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        pip install sphinx sphinx-rtd-theme
          
    - name: Build Sphinx documentation (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        cd docs
        make html
          
    - name: Upload Sphinx artifact (main branch only)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-docs
        path: docs/_build/html

    # Step 11: Deploy to GitHub Pages (only on main branch)
    - name: Deploy to GitHub Pages (main branch only)
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
        
    - name: Output deployment URL (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment completed successfully"
        echo "Page URL: ${{ steps.deployment.outputs.page_url }}"
