name: Code Quality

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies for ta-lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        sudo ./configure --prefix=/usr
        sudo make
        sudo make install
        sudo ldconfig

    - name: Install dependencies and linting tools
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas
        pip install TA-Lib
        pip install flake8 black
    
    - name: Run flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 pandas_ta_classic --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings for non-critical issues
        flake8 pandas_ta_classic --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=pandas_ta_classic/__init__.py
    
    - name: Check code formatting with black
      run: |
        black --check --diff pandas_ta_classic/

    - name: Install package and run basic tests
      run: |
        pip install -e .
        python -c "import pandas_ta_classic as ta; print('Package import successful')"
        python -m unittest tests.test_indicator_performance -v
